#ifndef AST_H
#define AST_H

enum ASTNodeType {
    ROOT_NODE,
    VARIABLE_DECLARATION_NODE,
    VARIABLE_ASSIGNMENT_NODE,
    BUFFER_WRITE_NODE,
    EXPRESSION_NODE,
    TERM_NODE,
    CONDITION_NODE,
    CONDITIONAL_NODE,
    BEGIN_END_BLOCK_NODE,
    PROCEDURE_CALL_NODE,
    WHILE_LOOP_NODE,
    PROCEDURE_NODE,
    BUFFER_READ_NODE
};

#endif // AST_H
