[package]
name = "cpu"
version = "0.1.0"
authors = ["Oliver Lok Trevor <featherfeet5436@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
num-traits = "0.2"
num-derive = "0.2"
