// Size of the text display.
`define GPU_TEXT_DISPLAY_ROWS 'd24
`define GPU_TEXT_DISPLAY_COLUMNS 'd80
`define GPU_DISPLAY_WIDTH_PIXELS 'd640
`define GPU_DISPLAY_HEIGHT_PIXELS 'd480

// The dimensions (in pixels) of each character cell.
`define GPU_CHARACTER_CELL_WIDTH (`GPU_DISPLAY_WIDTH_PIXELS / `GPU_TEXT_DISPLAY_COLUMNS)
`define GPU_CHARACTER_CELL_HEIGHT (`GPU_DISPLAY_HEIGHT_PIXELS / `GPU_TEXT_DISPLAY_ROWS)

// The length of the GPU text buffer.
`define GPU_TEXT_BUFFER_LENGTH (`GPU_TEXT_DISPLAY_ROWS * `GPU_TEXT_DISPLAY_COLUMNS)
