// Size of the text display.
`define GPU_TEXT_DISPLAY_ROWS 5'd24
`define GPU_TEXT_DISPLAY_COLUMNS 7'd80
`define GPU_DISPLAY_WIDTH_PIXELS 10'd640
`define GPU_DISPLAY_HEIGHT_PIXELS 9'd480

// The dimensions (in pixels) of each character cell.
`define GPU_CHARACTER_CELL_WIDTH (`GPU_DISPLAY_WIDTH_PIXELS / `GPU_TEXT_DISPLAY_COLUMNS)
`define GPU_CHARACTER_CELL_HEIGHT (`GPU_DISPLAY_HEIGHT_PIXELS / `GPU_TEXT_DISPLAY_ROWS)
